version: "3.7"

services:
  ess_db:
    image: postgres:${POSTGRES_IMG_TAG}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ess_backend
    healthcheck:
      test: ["CMD-SHELL", "su", "-", "postgres", "-c", "'pg_isready'", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout:  60s
      retries:  10
      start_period: 30s
    restart: unless-stopped

volumes:
  db-data:
    driver: local

networks:
  ess_backend:
    name: ess-backend-net
