[env]
ESS_ADMIN_WS_CERT="./scripts/admin/admin-server-bundle.pem"
ESS_ADMIN_WS_KEY="./scripts/admin/admin-server-key.pem"
ESS_ADMIN_WS_PORT="8081"
ESS_PAM_WS_CERT="./scripts/pam/pam-server-bundle.pem"
ESS_PAM_WS_KEY="./scripts/pam/pam-server-key.pem"
ESS_PAM_WS_PORT="8080"
